### ISSUE TITLE
Help with tweaking the header

### ISSUE THREAD

**Issue by enibache** [valentin2105/Simplekube#3]
Hi Valentin,
I get the following error after running ./install_k8s.sh: "The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?"
Actually i also used the ip address of the VM i'm running the script on but no success. 
Well FYI, i'm running an ubuntu box with vitualbox from my windows7 machine. Wondering if this could actually pose a problem! 
Could you specify if the value for the hostPI should be the VMs IP Address? I set this parameter to: hostIP="VMs_IPadress:8443" 
Looking forward to your response...
Many thanks by the way, for a gr8 job you did here!

**Comment by valentin2105** [comment]
Hi Enibache, 

Which version of Ubuntu you use ? 
Virtualbox normally doesn't create any problem on the installation side. 


have you setting the script like that : 

```
hostIP="192.168.1.10"
```

(You dont need to put the port, it's automaticaly 6443)

**Comment by enibache** [comment]
Hi Valentin,
thanks for your prompt response. Its an Ubuntu16.04. Initially i did without the port but got the same error, which is why i tried again with the port. thinking it could help. Attempting to add worker nodes also didn't succeed. Do i have to create the VMs and setup keybased authentication manually or is this done by the shell script?

Thanks once again !

**Comment by valentin2105** [comment]
- To add a node, you'll need to setup manually keybase authentification. 


About the script, I suggest you to re-start from scratch (or delete all file but it can be painfull). 

Just use the Internal IP of your VM at the `hostIP`variable. 
I have tested Ubuntu 16.04 and it should work from scratch. 

Take a look if you see any error during the script.

**Comment by enibache** [comment]
$HELM_HOME has been configured at /root/.helm.                                                                                                                       
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:8080: getsockopt: connection refused  
.
.
.
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Your cluster is up and running !
root@master:/opt/k8s/Simplekube# kubectl get cs
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by valentin2105** [comment]
Can you send me the hostIP variable like you used it ? 

Are you able to see if there is an error previously in the install process ? 

Thanks

**Comment by enibache** [comment]
the hostIP is the ip address of the  "master" node without the port as you rightly pointed out in your previous response. Furthermore, there was an error with etcd like so:  

> _etcd-v3.2.9-linux-amd64/README.md                                                                                                 
etcd-v3.2.9-linux-amd64/READMEv2-etcdctl.md                                                                                       
Created symlink from /etc/systemd/system/multi-user.target.wants/etcd.service to /etc/systemd/system/etcd.service.                
cluster may be unhealthy: failed to list members                                                                                  
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused   
; error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused                                                                                                                                                                                             
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused                                                                 
error #1: dial tcp 127.0.0.1:4001: getsockopt: _connection_ refused_                                                           
                                                                                                                          
could i be missing something before running the shell script?

**Comment by valentin2105** [comment]
Hum.. Pretty strange, it seem that ETCD crash so the other components can't start.

can you do that : 

```
service etcd stop 

cat /etc/systemd/system/etcd.service

(launch /usr/local/bin/etcd.... command present in the file the see the output and 
why etcd crash on your VM.) 
```

**Comment by enibache** [comment]
Thanks a lot Valentin for your fabulous efforts with this nice piece of scripts. It's really a time saver. I now got kubernetes running on my laptop but had to fix a few things;
- the link to dashboard "https://git.io/kube-dashboard" is deprecated, so i had to use a local copy.
- swap caused some issues so i had to switchoff swap on the master VM to get the kubelet running

One more question though, i'm still to get some workers installed but setting up key-based authentication is not quite clear. I'm bootstrapping my master VM and 2 worker VMs using vagrant and packer, so vagrant creates ssh key-based auth to the VMs from my local machine, but now i need to create key-based auth as well between my master and worker nodes. Could you help me with this? Is it simply creating another keypair on the master VM and installing the public key to my worker nodes? Or master-worker-master authentication? Do you have perhaps a working example with "root" as user or "xxx" as user? Thanks once again for saving me time. Looking forward to your response...

**Comment by valentin2105** [comment]
Hi @enibache Sorry for the delay.

I will do modification about swap to make it work directly. 

About the SSH KeyPair,
All you need is, Get a SSH key on your master (root) and allow your worker to get loggued from the Master.   (`ssh-keygen` & `ssh-copy-id root@workerIP`)

**Comment by enibache** [comment]
$HELM_HOME has been configured at /root/.helm.                                                                                                                       
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:8080: getsockopt: connection refused  
.
.
.
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Your cluster is up and running !
root@master:/opt/k8s/Simplekube# kubectl get cs
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by enibache** [comment]
ok, thanks Valentin. I simply used my vagrant private key on the master node and propagated the public keys of the worker nodes to the root user and it seems to work. However though, i can't seem to access the ui.
```
root@master:/vagrant/Simplekube# kubectl cluster-info
Kubernetes master is running at http://localhost:8080
KubeDNS is running at http://localhost:8080/api/v1/namespaces/kube-system/services/kube-dns/proxy
```

But i want to access it from my local browser on https://master:8080/ui. I wonder what i must do to tweak the setup to access the dashboard from my browser, not on the master VM's browser...

**Comment by valentin2105** [comment]
I think what your looking for is `kubectl proxy` and then reach `http://127.0.0.1:8001/ui/`

😄

**Comment by enibache** [comment]
Thanks Valentin, i finally got to the UI by creating a tunnel to my host on port 8001.

**Comment by valentin2105** [comment]
Can you close the issue if everything resolved. 😸

**Comment by enibache** [comment]
Oh sure, the dashboard is now available but still having lots of connection and communication issues that i must automate. I really appreciate your effort and assistance though. I'll now close this issue. Thanks!
