### ISSUE TITLE
Remove the cluster

### ISSUE THREAD

**Issue by krol3** [valentin2105/Simplekube#5]
Hi!! 
After I install with install_k8s.sh some machine, how could I remove the cluster?

**Comment by valentin2105** [comment]
Hi @krol3 ,

I have not created some deletion script, 

If you want totaly remove all the stuffs, you need to read a bit the script to don't forget any file , 

Otherwize, to stop all process, do that : 

```
systemctl disable kube-apiserver
systemctl disable kube-scheduler
systemctl disable kube-controller-manager
systemctl disable docker
systemctl disable kubelet
systemctl disable kube-proxy
systemctl disable calico
reboot
...
```
